channels:
  - conda-forge
dependencies:
  - python>=3.11.4,<3.12
  - nbconvert>=7.7.4,<8
  - nbstripout>=0.6.1,<0.7
  - notebook>=7.0.2,<8
  - pip:
    - attrs>=22.1.0
    - pydra==0.22
platforms:
  - linux-64
  - osx-64
